import pandas as pd
from pathlib import Path
import sys
import logging

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from collectors._base import get_project_root
from core.country_processor_contract import (
    CountryProcessorInput,
    assert_country_output_contract,
    finalize_country_output,
    save_country_output,
)
from core.edizm import load_common_edizm_mapping, resolve_edizm_record

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def load_china_codes_mapping(codes_dir: Path, common_edizm_map: dict = None) -> dict:
    """
    Load china codes mapping from CSV files to get EDIZM and EDIZM_ISO mapping.
    
    Args:
        codes_dir: Path to metadata/china-codes directory
        
    Returns:
        Dictionary mapping TNVED codes to units info
    """
    logger.info("Loading China codes mapping...")
    
    # Find all china codes CSV files
    csv_files = list(codes_dir.glob("*-china.csv"))
    if not csv_files:
        logger.warning("No china codes CSV files found")
        return {}
    
    # Process all CSV files and create mapping
    codes_mapping = {}
    
    for csv_file in csv_files:
        try:
            year = csv_file.stem.split('-')[0]
            logger.info(f"Processing {csv_file.name} (year: {year})")
            
            # Try different encodings and parsing options for CSV files
            encodings_to_try = ['utf-8', 'utf-8-sig', 'cp1252', 'cp1251', 'latin1', 'iso-8859-1']
            df = None
            successful_encoding = None
            
            for encoding in encodings_to_try:
                try:
                    df = pd.read_csv(csv_file, encoding=encoding, on_bad_lines='skip', quoting=1)
                    # Check if we got any data
                    if len(df) > 0 and 'CODES' in df.columns:
                        successful_encoding = encoding
                        logger.debug(f"Successfully loaded {csv_file.name} with {encoding} encoding ({len(df)} rows)")
                        break
                    df = None
                except (UnicodeDecodeError, pd.errors.ParserError, FileNotFoundError) as e:
                    logger.debug(f"Failed to load {csv_file.name} with {encoding}: {str(e)[:50]}...")
                    continue
            
            if df is None:
                logger.error(f"Could not decode {csv_file.name} with any encoding")
                continue
            
            # Create mapping for this year
            for _, row in df.iterrows():
                tnved_code = str(row['CODES']).zfill(8)  # Ensure 8 digits
                unit_description = row['UNIT_2_DESCRIPTION']
                unit_record = resolve_edizm_record(unit_description, common_edizm_map)
                
                codes_mapping[tnved_code] = {
                    'EDIZM': unit_record.get('NAME') if unit_record else unit_description,
                    'EDIZM_ISO': unit_record.get('KOD') if unit_record else '?'
                }
                
        except Exception as e:
            logger.error(f"Failed to process {csv_file.name}: {e}")
    
    # Report mapping coverage
    mapped_units = set()
    unmapped_units = set()
    
    for mapping in codes_mapping.values():
        if mapping['EDIZM_ISO'] != '?':
            mapped_units.add(mapping['EDIZM'])
        else:
            unmapped_units.add(mapping['EDIZM'])
    
    logger.info(f"Loaded codes mapping with {len(codes_mapping)} TNVED codes")
    logger.info(f"Successfully mapped units: {sorted(mapped_units)}")
    if unmapped_units:
        logger.warning(f"Unmapped units found: {sorted(unmapped_units)}")
        logger.warning("Consider adding these to COUNTRY_UNIT_ALIAS_RECORDS in core.normalization_rules")
    
    return codes_mapping

def process_and_merge_china_data(
    raw_data_dir: Path, 
    output_file: Path, 
    codes_dir: Path = None, 
    edizm_file: Path = None
):
    """
    Scans for raw china data files, processes them according to the logic
    from ProcessData.ipynb, merges them into a single DataFrame, and saves
    as a Parquet file.
    """
    
    # 0. Load China code and EDIZM mappings through the common EDIZM layer
    processor_input = CountryProcessorInput.from_paths(
        raw_data_dir,
        output_file,
        country_code="CN",
        edizm_file=edizm_file,
    )
    project_root = processor_input.metadata_dir.parent if processor_input.metadata_dir else Path.cwd()
    common_edizm_map = load_common_edizm_mapping(project_root)

    codes_mapping = {}
    if codes_dir and codes_dir.exists():
        codes_mapping = load_china_codes_mapping(codes_dir, common_edizm_map)
    
    # 1. Find all raw data files generated by the collector
    logger.info("Searching for raw data files...")
    import_dir = processor_input.raw_data_dir / 'IMPORT'
    export_dir = processor_input.raw_data_dir / 'EXPORT'
    
    all_files = list(import_dir.glob('data*.csv')) + list(export_dir.glob('data*.csv'))

    if not all_files:
        logger.error("No raw data files found to process in 'data_raw/china/'.")
        return

    logger.info(f"Found {len(all_files)} files to process.")
    
    # 2. Process each file and collect DataFrames
    processed_dfs = []
    for file_path in all_files:
        try:
            df = pd.read_csv(file_path)

            # Apply transformations based on refresh_ch()
            if 'PERIOD' in df.columns:
                df['PERIOD'] = df['PERIOD'] + '-01'
            
            if 'STRANA' in df.columns:
                df['STRANA'] = 'CN'

            # Rename columns to match the old notebook's standard
            df = df.rename(columns={
                'Supplementary Quantity': 'KOL',
                # We no longer need 'Supplementary Unit' as EDIZM will be derived
            })

            # Ensure the TNVED code is a zero-padded 8-digit string.
            # TNVED2/4/6 are recomputed from TNVED by finalize_country_output.
            if 'TNVED' in df.columns:
                df['TNVED'] = df['TNVED'].astype(str).str.zfill(8)
            
            # Initialize EDIZM and EDIZM_ISO columns
            df['EDIZM_ISO'] = '?'
            df['EDIZM'] = '?'
            
            # Add EDIZM and EDIZM_ISO from mappings
            if codes_mapping and 'TNVED' in df.columns:
                logger.info(f"Applying units mapping for {file_path.name}")
                
                # Get the ISO code from the TNVED mapping
                df['EDIZM_ISO'] = df['TNVED'].map(
                    lambda x: codes_mapping.get(str(x).zfill(8), {}).get('EDIZM_ISO', '?')
                )
                
                df['EDIZM'] = df['TNVED'].map(
                    lambda x: codes_mapping.get(str(x).zfill(8), {}).get('EDIZM', '?')
                )

            # Reorder columns to a standard format
            standard_columns = [
                'NAPR', 'PERIOD', 'STRANA', 'TNVED', 'EDIZM', 'EDIZM_ISO', 'STOIM', 
                'NETTO', 'KOL', 'TNVED4', 'TNVED6', 'TNVED2'
            ]
            
            existing_cols = [col for col in standard_columns if col in df.columns]
            df = df.reindex(columns=existing_cols)
            
            processed_dfs.append(df)
            logger.info(f"  - Processed {file_path.name}")
        except Exception as e:
            logger.error(f"  - FAILED to process {file_path.name}: {e}")

    if not processed_dfs:
        logger.error("No data was successfully processed.")
        return

    # 3. Concatenate all DataFrames
    logger.info("Merging all processed files...")
    final_df = pd.concat(processed_dfs, ignore_index=True)

    # 4. Clean data before saving
    # The NETTO column can contain non-numeric characters (e.g., tabs)
    # Convert to string, strip whitespace, and then convert to numeric, coercing errors.
    if 'NETTO' in final_df.columns:
        logger.info("Cleaning 'NETTO' column...")
        final_df['NETTO'] = pd.to_numeric(
            final_df['NETTO'].astype(str).str.strip(), 
            errors='coerce'
        )

    if 'KOL' in final_df.columns:
        logger.info("Cleaning 'KOL' column...")
        final_df['KOL'] = pd.to_numeric(
            final_df['KOL'].astype(str).str.strip(),
            errors='coerce'
        )

    final_df = finalize_country_output(
        final_df,
        country_code=processor_input.country_code,
        sort_by=("PERIOD", "NAPR", "TNVED"),
    )
    assert_country_output_contract(final_df, expected_strana=processor_input.country_code)

    # 5. Check for missing months in the time series
    logger.info("Checking for gaps in the time series...")
    if 'PERIOD' in final_df.columns:
        # Ensure PERIOD is in datetime format for comparison
        final_df['PERIOD'] = pd.to_datetime(final_df['PERIOD'])
        
        # Get the unique months from the data
        actual_months = set(final_df['PERIOD'].dt.to_period('M'))
        
        # Create a complete date range from min to max date
        start_date = final_df['PERIOD'].min()
        end_date = final_df['PERIOD'].max()
        expected_months = set(pd.period_range(start=start_date, end=end_date, freq='M'))
        
        missing_months = sorted(list(expected_months - actual_months))
        
        if missing_months:
            logger.warning("Missing data for the following months:")
            for month in missing_months:
                logger.warning(f"  - {month}")
        else:
            logger.info("No missing months found in the time series.")

    # 6. Save final DataFrame as Parquet
    try:
        save_country_output(final_df, processor_input.output_file, logger=logger)
        logger.info("Processing complete.")
        
        # Summary statistics
        logger.info(f"Final dataset: {len(final_df)} rows")
        if 'EDIZM_ISO' in final_df.columns:
            non_null_edizm_iso = final_df['EDIZM_ISO'].notna().sum()
            mapped_iso = (final_df['EDIZM_ISO'] != '?').sum()
            logger.info(f"EDIZM_ISO mapping: {mapped_iso}/{len(final_df)} rows ({mapped_iso/len(final_df)*100:.1f}%) successfully mapped")
            logger.info(f"EDIZM_ISO filled: {non_null_edizm_iso}/{len(final_df)} rows ({non_null_edizm_iso/len(final_df)*100:.1f}%) have values")
        
    except ImportError:
        logger.error("'pyarrow' is required to save to Parquet format.")
        logger.error("Please install it using: pip install pyarrow")


def main():
    """
    Main function to run the China data processing script.
    """
    project_root = get_project_root()
    raw_data_dir = project_root / 'data_raw' / 'china'
    codes_dir = project_root / 'metadata' / 'china-codes'
    edizm_file = project_root / 'metadata' / 'edizm.csv'
    output_file = project_root / 'data_processed' / 'cn_full.parquet'  # Using ISO 3166-1 alpha-2 code
    
    process_and_merge_china_data(raw_data_dir, output_file, codes_dir, edizm_file)

if __name__ == "__main__":
    main()
