# -*- coding: utf-8 -*-
"""India Processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cr6KxUTlAaz-vC9akoHyp33OpYcWePX_
"""

import pandas as pd
from pathlib import Path
import os
import sys
import logging

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.country_processor_contract import (
    CountryProcessorInput,
    finalize_country_output,
    save_country_output,
)
from core.edizm import load_common_edizm_mapping, resolve_edizm_records

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def process_and_merge_india_data(raw_data_dir: Path, output_file: Path, edizm_file: Path):
    """
    Сканирует директорию с необработанными данными, обрабатывает каждый CSV-файл,
    объединяет их в один DataFrame и сохраняет в формате Parquet.
    """

    logger.info("=== Начало обработки данных Индии ===")

    processor_input = CountryProcessorInput.from_paths(
        raw_data_dir,
        output_file,
        country_code="IN",
        edizm_file=edizm_file,
    )
    
    project_root = processor_input.metadata_dir.parent if processor_input.metadata_dir else Path.cwd()
    common_edizm_map = load_common_edizm_mapping(project_root)

    all_files = sorted(processor_input.raw_data_dir.glob("india_*.csv"))
    if not all_files:
        logger.error(f"Не найдено файлов в {processor_input.raw_data_dir}")
        return

    logger.info(f"Найдено {len(all_files)} файлов для объединения")

    dfs = []
    for file_path in all_files:
        try:
            df = pd.read_csv(file_path, dtype={
                'TNVED': str,
                'TNVED2': str,
                'TNVED4': str,
                'TNVED6': str
            })
            logger.info(f"  → {file_path.name}: {len(df)} строк")

            df['PERIOD'] = pd.to_datetime(
                df['Year'].astype(str) + '-' + df['Month'].astype(str).str.zfill(2) + '-01',
                errors='coerce'
            )


            for col in ['STOIM', 'STOIM_NAC_VAL', 'NETTO', 'KOL']:
                if col in df.columns:
                    df[col] = pd.to_numeric(df[col], errors='coerce')

            # STOIM -> тысячи USD (стандарт проекта).
            # Для текущего архива india_new:
            # - до 2026-01 значения уже в тысячах USD -> без умножения
            # - с 2026-01 значения в млн USD -> *1000
            if 'STOIM' in df.columns:
                file_year = int(df['Year'].iloc[0]) if 'Year' in df.columns and len(df) else 0
                file_month = int(df['Month'].iloc[0]) if 'Month' in df.columns and len(df) else 0
                if (file_year, file_month) >= (2026, 1):
                    df['STOIM'] = df['STOIM'] * 1000

            # Map units through the common EDIZM normalization layer.
            if 'EDIZM' in df.columns:
                original_edizm = df['EDIZM'].astype(str).str.strip().replace({'nan': '?', 'None': '?'})
            else:
                original_edizm = pd.Series('?', index=df.index)

            edizm_records = resolve_edizm_records(original_edizm, common_edizm_map)
            df['EDIZM_ISO'] = edizm_records.map(
                lambda record: record.get('KOD') if isinstance(record, dict) else None
            )
            df['EDIZM'] = edizm_records.map(
                lambda record: record.get('NAME') if isinstance(record, dict) else None
            ).fillna(original_edizm)

            df_final = df[[
                'NAPR', 'PERIOD', 'STRANA', 'TNVED',
                'EDIZM', 'EDIZM_ISO', 'STOIM', 'NETTO',
                'KOL', 'TNVED4', 'TNVED6', 'TNVED2'
            ]].copy()

            period_label = df_final['PERIOD'].iloc[0].strftime('%Y-%m') if len(df_final) else "?"
            total_stoim = df_final['STOIM'].sum()
            logger.info(f"     STOIM сумма за {period_label}: {total_stoim:,.0f} (тыс. USD)")

            dfs.append(df_final)

        except Exception as e:
            logger.error(f"Ошибка при обработке {file_path.name}: {e}")

    if not dfs:
        logger.error("Не удалось обработать ни один файл.")
        return

    final_df = finalize_country_output(
        pd.concat(dfs, ignore_index=True),
        country_code=processor_input.country_code,
    )

    # Сводка по месяцам — для проверки размерности (резкий скачок/провал = возможная ошибка масштаба)
    stoim_by_month = final_df.groupby(final_df['PERIOD'].dt.to_period('M'))['STOIM'].sum()
    logger.info("STOIM по месяцам (тыс. USD), для проверки размерности:")
    for period, total in stoim_by_month.items():
        logger.info(f"  {period}: {total:,.0f}")

    save_country_output(final_df, processor_input.output_file, logger=logger)

def main():
    """
    Точка входа в скрипт. Определяет пути к данным и запускает
    процесс обработки и слияния.
    """
    try:
        project_root = Path(__file__).resolve().parent.parent.parent
    except NameError:
        project_root = Path(os.getcwd())

    raw_data_dir = project_root / 'data_raw' / 'india_new'
    output_file = project_root / 'data_processed' / 'in_full.parquet'
    edizm_file = project_root / 'metadata' / 'edizm.csv'

    process_and_merge_india_data(raw_data_dir, output_file, edizm_file)


if __name__ == "__main__":
    main()
