name: Quarto Publish

on:
  push:
    branches: [ main ]
    paths:
      - "site/**/*.qmd"
      - "site/styles/**/*.scss"
      - "site/styles/**/*.css"
      - "site/data/**/*.csv"
      - "other/**/*.qmd"
      - "lessons/**/*.qmd"
      - "lessons/**/*.css"
      - "_quarto.yml"
      - "site/_quarto.yml"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # нужно для пуша в gh-pages

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto (pin version)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.34"   # latest - не работает почему-то

      - name: Show Quarto version (debug)
        run: quarto --version

      # Рендерим весь проект (но что именно рендерить — лучше указать в _quarto.yml -> project.render)
      - name: Render site
        run: quarto render . --no-execute

      # Публикуем уже собранный _site без повторного рендера
      - name: Publish _site to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
